name: GLavaRise
version: '${project.version}'
main: net.grayclouds.gLavaRise.GLavaRise
api-version: '1.20'

commands:
  start:
    description: Start the lava/void rise
    usage: /<command>
    permission: glavarise.start
  pause:
    description: Pause the lava/void rise
    usage: /<command>
    permission: glavarise.pause
  end:
    description: End the lava/void rise
    usage: /<command>
    permission: glavarise.end
  reload:
    description: Reload the plugin configuration
    usage: /<command>
    permission: glavarise.reload
  team:
    description: Team management commands
    usage: /<command> <join|leave|list>
    permission: glavarise.team

permissions:
  glavarise.start:
    description: Allows starting the lava rise event
    default: op
  glavarise.pause:
    description: Allows pausing the lava rise event
    default: op
  glavarise.end:
    description: Allows ending the lava rise event
    default: op
  glavarise.reload:
    description: Allows reloading the configuration
    default: op
