# gLavaRise config file (config.yml)
# Plugin made by GrayClouds

# This is the main configuration file.
# Other settings can be found in:
# - game.yml: General game settings
# - worlds.yml: World-specific settings
# - messages.yml: All plugin messages
# - teams.yml: Team configuration
# - sounds.yml: Sound settings
# - titles.yml: Title and subtitle settings

VERSION: 'v2.0'