# gLavaRise config file (config.yml)
# Plugin made by GrayClouds

CONFIG:
  WORLDS:
    OVERWORLD:
      enabled: true
      RISE-INTERVAL: 15
      BORDER:
        initial-size: 250
        shrink-enabled: true
        shrink:
          method: "TIME"
          time-interval: 300
          shrink-amount: 50
          minimum-size: 50
          players-threshold: 5
      LAVA:
        replace-all-blocks: true
      BORDER-DAMAGE:
        enabled: true
        damage-radius: 5
        damage-amount: 2
        damage-interval: 1

    NETHER:
      enabled: false  # Toggle nether functionality
      RISE-INTERVAL: 10  # Faster in nether
      BORDER:
        initial-size: 200
        shrink-enabled: true
        shrink:
          method: "TIME"
          time-interval: 240
          shrink-amount: 40
          minimum-size: 40
          players-threshold: 5
      LAVA:
        replace-all-blocks: true
      BORDER-DAMAGE:
        enabled: true
        damage-radius: 5
        damage-amount: 3  # More damage in nether
        damage-interval: 1

    END:
      enabled: false  # Toggle end functionality
      RISE-INTERVAL: 20  # Slower in end
      BORDER:
        initial-size: 300
        shrink-enabled: true
        shrink:
          method: "TIME"
          time-interval: 360
          shrink-amount: 60
          minimum-size: 60
          players-threshold: 5
      LAVA:
        replace-all-blocks: true
      BORDER-DAMAGE:
        enabled: true
        damage-radius: 5
        damage-amount: 2
        damage-interval: 1

  MESSAGES:
    lava-end: "Lava rise has been ended!"
    lava-start: "Lava rise has started!"
    lava-pause: "Lava rise has been paused!"
    lava-not-active: "Lava rise is not currently active!"
    border-shrink: "The border is shrinking!"
    border-minimum: "The border has reached its minimum size!"
    height-warning: "Current lava height: %height%"
    border-warning: "§cYou're too close to the border!"
    player-only: "This command can only be used by players!"
    no-permission: "You don't have permission to use this command!"
    player-eliminated: "%player% has been eliminated!"
    players-remaining: "%count% players remaining!"