name: GLavaRise
version: 'v1.2'
main: net.grayclouds.gLavaRise.GLavaRise
api-version: '1.20'

commands:
  startlava:
    description: Start the lava/void rise
    usage: /<command>
    permission: glavarise.start
  pauselava:
    description: Pause the lava/void rise
    usage: /<command>
    permission: glavarise.pause
  endlava:
    description: End the lava/void rise
    usage: /<command>
    permission: glavarise.end
  reloadlava:
    description: Reload the plugin configuration
    usage: /<command>

permissions:
  glavarise.start:
    description: Allows starting the lava rise event
    default: op
  glavarise.pause:
    description: Allows pausing the lava rise event
    default: op
  glavarise.end:
    description: Allows ending the lava rise event
    default: op
